{
 "title": "Kubernetes / Rightsizing",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Namespace CPU Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage over Requests (namespace)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)) / sort_desc (sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"})) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused CPU by Namespace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}) - sum by (namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage over Requests (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)  / sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused CPU by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "sort_desc( sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}) - sum by (namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespace Memory Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RAM Usage over Requests (namespace)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) / sort_desc (sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused Memory by Namespace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}) - sum by (namespace)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"})) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage over Requests (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) / sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage over Requests (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Mi" } },
   "targets": [
    {
     "expr": "sort_desc (sum by (namespace) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}) - sum by (namespace)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"})) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage over Limits (namespace)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) / sum by (namespace) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage over Limits (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) / sum by (namespace) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workload Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage over Requests (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n/sum( kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage over Limits (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n/sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage over Requests (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n/sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage over Limits (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n/sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}